//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBox_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Emp_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Contact_number { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
