//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBox_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Movie_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<System.DateTime> Release_year { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string Poster { get; set; }
        public Nullable<short> Language_id { get; set; }
        public Nullable<short> Category_id { get; set; }
        public Nullable<short> Actor_id { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
    }
}
